name = "d-ink"
main = "src/worker.ts"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "d-ink-v1"
database_id = "b7a61b67-93a1-4e0e-a6dd-5dbb6f67da3b"
migrations_dir = "src/db/migrations"

[[r2_buckets]]
binding = "ANNUAL_REPORT_FILES"
bucket_name = "d-ink-annual-report-files"
preview_bucket_name = "d-ink-annual-report-files-preview"

[[queues.producers]]
binding = "ANNUAL_REPORT_QUEUE"
queue = "d-ink-annual-report-processing"

[[queues.consumers]]
queue = "d-ink-annual-report-processing"
max_batch_size = 1
max_batch_timeout = 1
