import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";

import { parseTrialBalanceFileV1 } from "../../../src/server/parsing/trial-balance-parser.v1";

function createWorkbookBytesV1(input: {
  sheets: Record<string, unknown[][]>;
}): Uint8Array {
  const workbook = XLSX.utils.book_new();

  for (const [sheetName, rows] of Object.entries(input.sheets)) {
    const sheet = XLSX.utils.aoa_to_sheet(rows);
    XLSX.utils.book_append_sheet(workbook, sheet, sheetName);
  }

  const bytes = XLSX.write(workbook, {
    bookType: "xlsx",
    type: "array",
  });

  return new Uint8Array(bytes);
}

function createWorkbookBytesFromWorkbookV1(
  workbook: XLSX.WorkBook,
): Uint8Array {
  const bytes = XLSX.write(workbook, {
    bookType: "xlsx",
    type: "array",
  });

  return new Uint8Array(bytes);
}

describe("trial balance parser v1", () => {
  it("parses xlsx, normalizes mixed numeric formats, and suffixes duplicates", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        "Trial Balance": [
          [
            "Account Name",
            "Account Number",
            "Opening Balance",
            "Closing Balance",
          ],
          ["Cash", "1001", "1 234,56", "1,500.25"],
          ["Cash - branch", "1001", "(100,00)", "-50"],
          ["Total", "", "1 134,56", "1,450.25"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "tb.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.rows).toHaveLength(2);
    expect(result.trialBalance.rows[0]?.accountNumber).toBe("1001.1");
    expect(result.trialBalance.rows[1]?.accountNumber).toBe("1001.2");
    expect(result.trialBalance.rows[0]?.openingBalance).toBe(1234.56);
    expect(result.trialBalance.rows[1]?.openingBalance).toBe(-100);
    expect(result.trialBalance.rows[1]?.closingBalance).toBe(-50);
    expect(result.trialBalance.rejectedRows).toHaveLength(1);
    expect(result.trialBalance.rejectedRows[0]?.reasonCode).toBe(
      "SUMMARY_ROW_EXCLUDED",
    );
    expect(result.trialBalance.verification.duplicateAccountNumberGroups).toBe(
      1,
    );
  });

  it("selects the best sheet and supports Swedish headers in different order", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        Metadata: [["Generated by system"], ["Do not parse"]],
        Bokslut: [
          ["Kommentar", "Valuta", "Datum"],
          ["Kontonummer", "Kontonamn", "Ingående Balans", "Utgående Balans"],
          ["1930", "Bank", "12 000,00", "15 500,00"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "swedish.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.selectedSheetName).toBe("Bokslut");
    expect(result.trialBalance.headerRowNumber).toBe(2);
    expect(result.trialBalance.rows).toHaveLength(1);
    expect(result.trialBalance.rows[0]?.accountName).toBe("Bank");
    expect(result.trialBalance.rows[0]?.accountNumber).toBe("1930");
    expect(result.trialBalance.rows[0]?.closingBalance).toBe(15500);
  });

  it("returns VERIFICATION_FAILED when candidate rows contain invalid numeric values", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        "Trial Balance": [
          [
            "Account Name",
            "Account Number",
            "Opening Balance",
            "Closing Balance",
          ],
          ["Bank", "1930", "12x", "1000"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "invalid-numeric.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(false);
    if (result.ok) {
      return;
    }

    expect(result.error.code).toBe("VERIFICATION_FAILED");
  });

  it("excludes summary rows even when they contain account numbers", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        "Trial Balance": [
          [
            "Account Name",
            "Account Number",
            "Opening Balance",
            "Closing Balance",
          ],
          ["Cash", "1001", "1000", "1200"],
          ["Total assets", "9999", "1000", "1200"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "summary-account-row.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.rows).toHaveLength(1);
    expect(result.trialBalance.rows[0]?.accountNumber).toBe("1001");
    expect(result.trialBalance.rejectedRows[0]?.reasonCode).toBe(
      "SUMMARY_ROW_EXCLUDED",
    );
  });

  it("keeps legitimate account rows even when account names include summary-like terms", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        "Trial Balance": [
          [
            "Account Name",
            "Account Number",
            "Opening Balance",
            "Closing Balance",
          ],
          ["Resultat från andelar i koncernföretag", "8020", "250", "400"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "resultat-account.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.rows).toHaveLength(1);
    expect(result.trialBalance.rows[0]?.accountNumber).toBe("8020");
    expect(result.trialBalance.rejectedRows).toHaveLength(0);
  });

  it("supports combined account-number-and-name column", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        Data: [
          ["Account", "Opening Balance", "Closing Balance"],
          ["1001 Cash", "1000", "1200"],
          ["1002 - Accounts receivable", "800", "780"],
          ["1003/Inventory", "1200", "1150"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "combined-account-column.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.rows).toHaveLength(3);
    expect(result.trialBalance.rows[0]?.accountNumber).toBe("1001");
    expect(result.trialBalance.rows[0]?.accountName).toBe("Cash");
    expect(result.trialBalance.rows[1]?.accountNumber).toBe("1002");
    expect(result.trialBalance.rows[1]?.accountName).toBe(
      "Accounts receivable",
    );
    expect(result.trialBalance.rows[2]?.accountNumber).toBe("1003");
    expect(result.trialBalance.rows[2]?.accountName).toBe("Inventory");
  });

  it("fails verification when required balances are blank", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        "Trial Balance": [
          [
            "Account Name",
            "Account Number",
            "Opening Balance",
            "Closing Balance",
          ],
          ["Cash", "1001", "", "1200"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "blank-balance.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(false);
    if (result.ok) {
      return;
    }

    expect(result.error.code).toBe("VERIFICATION_FAILED");
    const rejectedRows = result.error.context.rejectedRows as Array<{
      reasonCode: string;
    }>;
    expect(rejectedRows[0]?.reasonCode).toBe("OPENING_BALANCE_MISSING");
  });

  it("finds headers beyond 40 rows by scanning deeper preambles", () => {
    const preambleRows = Array.from({ length: 60 }, (_, index) => [
      `Preamble ${index + 1}`,
      "",
      "",
      "",
    ]);

    const fileBytes = createWorkbookBytesV1({
      sheets: {
        Upload: [
          ...preambleRows,
          [
            "Account Name",
            "Account Number",
            "Opening Balance",
            "Closing Balance",
          ],
          ["Cash", "1001", "1000", "1200"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "deep-header.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.headerRowNumber).toBe(61);
    expect(result.trialBalance.rows).toHaveLength(1);
  });

  it("preserves formatted account numbers with leading zeroes", () => {
    const workbook = XLSX.utils.book_new();
    const sheet = XLSX.utils.aoa_to_sheet([
      ["Account Name", "Account Number", "Opening Balance", "Closing Balance"],
      ["Bank", 101, 1000, 1200],
    ]);
    (sheet.B2 as XLSX.CellObject).z = "0000";
    XLSX.utils.book_append_sheet(workbook, sheet, "TB");

    const result = parseTrialBalanceFileV1({
      fileName: "leading-zero.xlsx",
      fileBytes: createWorkbookBytesFromWorkbookV1(workbook),
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.rows[0]?.sourceAccountNumber).toBe("0101");
    expect(result.trialBalance.rows[0]?.accountNumber).toBe("0101");
  });

  it("uses sheet-name preference as tie-breaker when scores are equal", () => {
    const rows = [
      ["Account Name", "Account Number", "Opening Balance", "Closing Balance"],
      ["Cash", "1001", "1000", "1200"],
    ];

    const fileBytes = createWorkbookBytesV1({
      sheets: {
        Data: rows,
        "Trial Balance": rows,
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "tie-break.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.selectedSheetName).toBe("Trial Balance");
  });

  it("returns REQUIRED_COLUMN_MISSING when headers cannot be matched", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        Data: [
          ["Name", "Number", "Start", "End"],
          ["Bank", "1930", "100", "200"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "unknown-headers.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(false);
    if (result.ok) {
      return;
    }

    expect(result.error.code).toBe("REQUIRED_COLUMN_MISSING");
  });

  it("supports csv input via extension inference", () => {
    const csv = [
      "Account Name,Account Number,Opening Balance,Closing Balance",
      "Bank,1930,1000.25,1100.5",
    ].join("\n");

    const result = parseTrialBalanceFileV1({
      fileName: "tb.csv",
      fileBytes: new TextEncoder().encode(csv),
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.fileType).toBe("csv");
    expect(result.trialBalance.rows).toHaveLength(1);
    expect(result.trialBalance.rows[0]?.openingBalance).toBe(1000.25);
  });

  it("parses widened numeric formats (currency codes, apostrophe thousands, unicode minus)", () => {
    const fileBytes = createWorkbookBytesV1({
      sheets: {
        "Trial Balance": [
          [
            "Account Name",
            "Account Number",
            "Opening Balance",
            "Closing Balance",
          ],
          ["Bank", "1930", "SEK1'200,50", "−1'050,25"],
        ],
      },
    });

    const result = parseTrialBalanceFileV1({
      fileName: "widened-numeric.xlsx",
      fileBytes,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.trialBalance.rows).toHaveLength(1);
    expect(result.trialBalance.rows[0]?.openingBalance).toBe(1200.5);
    expect(result.trialBalance.rows[0]?.closingBalance).toBe(-1050.25);
  });

  it("returns UNSUPPORTED_FILE_FORMAT for unknown extension", () => {
    const result = parseTrialBalanceFileV1({
      fileName: "tb.pdf",
      fileBytes: new Uint8Array([1, 2, 3]),
    });

    expect(result.ok).toBe(false);
    if (result.ok) {
      return;
    }

    expect(result.error.code).toBe("UNSUPPORTED_FILE_FORMAT");
  });
});
